%%{init: {'themeVariables': {'fontSize': '34px'}}, 'flowchart': {'nodeSpacing': 40, 'rankSpacing': 70}}%%
flowchart LR
    EXT(["외부 테스트 장치"]):::node
    PS["PS"]:::dim
    GPIO["GPIO"]:::dim

    subgraph PLB ["PL"]
        direction TB
        LED["LED"]:::node
        DIP["DIP Switch"]:::node
        PB["Push Button"]:::node
        SEG["7-Segment"]:::node
        MIP["Master IP"]:::dim

        PB --> MIP
        DIP --> SEG
        MIP --> SEG
    end

    EXT <--> PS
    PS <--> MIP
    GPIO <--> LED
    GPIO <--> MIP
classDef node fill:#FFFFFF,stroke:#111111,stroke-width:1.5px,color:#111111,font-weight:bold,font-size:34px
classDef dim fill:#F2F2F2,stroke:#AAAAAA,color:#777777,font-weight:bold,font-size:34px
