# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/SoC_Design_and_Programming/Project/ps_tftlcd/ps_tftlcd.srcs/sources_1/bd/system/ip/system_tftlcd_0_3/system_tftlcd_0_3.xci
# IP: The module: 'system_tftlcd_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/SoC_Design_and_Programming/Project/ps_tftlcd/ps_tftlcd.srcs/sources_1/bd/system/ip/system_tftlcd_0_3/src/blk_mem_1/blk_mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem || ORIG_REF_NAME==blk_mem} -quiet] -quiet

# XDC: c:/SoC_Design_and_Programming/Project/ps_tftlcd/ps_tftlcd.srcs/sources_1/bd/system/ip/system_tftlcd_0_3/src/blk_mem_1/blk_mem_ooc.xdc

# IP: c:/SoC_Design_and_Programming/Project/ps_tftlcd/ps_tftlcd.srcs/sources_1/bd/system/ip/system_tftlcd_0_3/system_tftlcd_0_3.xci
# IP: The module: 'system_tftlcd_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/SoC_Design_and_Programming/Project/ps_tftlcd/ps_tftlcd.srcs/sources_1/bd/system/ip/system_tftlcd_0_3/src/blk_mem_1/blk_mem.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem || ORIG_REF_NAME==blk_mem} -quiet] -quiet

# XDC: c:/SoC_Design_and_Programming/Project/ps_tftlcd/ps_tftlcd.srcs/sources_1/bd/system/ip/system_tftlcd_0_3/src/blk_mem_1/blk_mem_ooc.xdc
