set_property SRC_FILE_INFO {cfile:C:/SoC_Design_and_Programming/Project/interrupt/interrupt.srcs/constrs_1/imports/interrupt/top.xdc rfile:../../../interrupt.srcs/constrs_1/imports/interrupt/top.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "AA19" [get_ports "pb_0[3]"]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y19" [get_ports "pb_0[2]"]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "AA18" [get_ports "pb_0[1]"]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y18" [get_ports "pb_0[0]"]
